Synthetic aurora
SwRI-IDEA-Lab/Aurora-NeRF pull request #1
Opened 2024-05-23 23:33 UTC by amunozj

Implementation of simple tubular aurora and associated test

2024-05-23 23:39 UTC, dcsozturk commented
Please add documentation.

2024-05-23 23:40 UTC, dcsozturk requested changes
Please add comments.

2024-05-24 00:30 UTC, amunozj commented
Documentation has ben added

2024-05-24 00:30 UTC, dcsozturk approved these changes
Docustring is sufficient.

2024-05-24 00:30 UTC, merged